"""Build a bounded, split raw resource bundle; no filesystem formatting on device."""
from pathlib import Path
import json
import struct
import sys
import zlib

ROOT = Path(__file__).resolve().parent.parent
FIRST = 0x2c0000
TAIL = 0x80000
HEADER = 4096

def packets(data):
    pos = 0
    while pos < len(data):
        if pos + 2 > len(data):
            raise ValueError('Truncated packet length')
        size = int.from_bytes(data[pos:pos+2], 'little')
        pos += 2
        if not 0 < size <= 1500 or size > len(data)-pos:
            raise ValueError('Invalid/truncated Opus packet')
        yield data[pos:pos+size]
        pos += size

def write(path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists() or path.read_bytes() != data:
        path.write_bytes(data)

def build(destination):
    assets = ROOT / 'assets/audio/voice-keychain'
    index = json.loads((assets/'voice_index.json').read_text(encoding='utf-8'))
    payload = bytearray()
    clips, packs, paths = [], [], set()
    for pack in index:
        packs.append((pack['dir'], len(clips), len(pack['files'])))
        for item in pack['files']:
            path = (assets/item['path']).resolve()
            if not path.is_relative_to(assets.resolve()) or path in paths:
                raise ValueError('Unsafe or duplicate resource path')
            paths.add(path)
            data = path.read_bytes()
            if not data or len(data) != item['compressed_bytes']:
                raise ValueError('Incorrect clip length')
            list(packets(data))
            clips.append((item['name'], HEADER+len(payload), len(data), item['samples']))
            payload.extend(data)
    assert paths == {p.resolve() for p in assets.rglob('*.opus')}
    assert len(packs) == 24 and len(clips) == 695
    identity = zlib.crc32(json.dumps([packs, clips], ensure_ascii=False).encode())
    header = struct.pack('<4sIIIII', b'VKP1', 1, len(clips), len(payload), identity, zlib.crc32(payload))
    header += struct.pack('<I', zlib.crc32(header))
    bundle = header.ljust(HEADER, b'\xff') + payload
    if len(bundle) > FIRST+TAIL:
        raise ValueError('Voice resources exceed available flash')
    bundle = bundle.ljust(FIRST+TAIL, b'\xff')
    write(destination/'voice_data.bin', bundle[:FIRST])
    write(destination/'voice_tail.bin', bundle[FIRST:])
    h = f'''/* Generated by tools/build_voice_pack.py. */
#pragma once
#include <stdint.h>
#define VOICE_FIRST_BYTES {FIRST}u
#define VOICE_TAIL_BYTES {TAIL}u
#define VOICE_TOTAL_BYTES {FIRST+TAIL}u
#define VOICE_SUMMARY "{len(packs)} 个分类 / {len(clips)} 段音效"
#define VOICE_CLIP_LABEL "{len(clips)} 段音效"
#define VOICE_PACK_COUNT {len(packs)}u
#define VOICE_CLIP_COUNT {len(clips)}u
#define VOICE_CATALOG_CRC {identity}u
#define VOICE_PAYLOAD_BYTES {len(payload)}u
typedef struct {{const char *name; uint32_t offset, length, samples;}} voice_clip_t;
typedef struct {{const char *name; unsigned first, count;}} voice_pack_t;
extern const voice_clip_t voice_clips[VOICE_CLIP_COUNT];
extern const voice_pack_t voice_packs[VOICE_PACK_COUNT];
'''
    quote = lambda s: '"'+''.join('\\x%02x'%v for v in s.encode())+'"'
    c = '#include "voice_catalog.h"\nconst voice_clip_t voice_clips[VOICE_CLIP_COUNT]={\n'
    c += ''.join('{%s,%du,%du,%du},\n'%(quote(n),o,l,s) for n,o,l,s in clips)+'};\n'
    c += 'const voice_pack_t voice_packs[VOICE_PACK_COUNT]={\n'
    c += ''.join('{%s,%du,%du},\n'%(quote(n),f,cnt) for n,f,cnt in packs)+'};\n'
    write(destination/'voice_catalog.h', h.encode())
    write(destination/'voice_catalog.c', c.encode())
    print(f'Voice bundle: {len(packs)} packs / {len(clips)} clips / {len(payload)} audio bytes')

if __name__ == '__main__':
    build(Path(sys.argv[1]) if len(sys.argv)>1 else ROOT/'build')
