from pathlib import Path
import sys,re
from PIL import Image,ImageDraw,ImageFont
root=Path(__file__).resolve().parent.parent
for size,weight in [(10,500),(28,800)]:
    f=ImageFont.truetype(sys.argv[1],size); f.set_variation_by_axes([weight])
    chars=set(chr(n) for n in range(32,127))
    if size==10:
        chars.update("长按切换上小程序菜单下亮码")
        hints=(root/'main/badge_footer.h').read_text(encoding='utf-8')
        for text in re.findall(r'#define BADGE_HINT_\w+ "([^"\n]+)"',hints): chars.update(text)
    if size==28:
        chars.update("小智")
        chars.update("圣杯笑阴阳未投掷")
        profile=(root/'main/badge_profile.h').read_text(encoding='utf-8-sig')
        chars.update(re.search(r'#define BADGE_DISPLAY_NAME \"([^\"]*)\"',profile).group(1))
    chars=sorted(chars)
    data=[]; glyphs=['{0}']
    for n in map(ord,chars):
        ch=chr(n); l,t,r,b=f.getbbox(ch,anchor='ls'); w,h=r-l,b-t
        im=Image.new('L',(max(1,w),max(1,h)))
        ImageDraw.Draw(im).text((-l,-t),ch,font=f,fill=255,anchor='ls')
        pix=[round(p/17) for p in im.getdata()] if w and h else []
        idx=len(data)
        if len(pix)%2: pix.append(0)
        data.extend((pix[i]<<4)|pix[i+1] for i in range(0,len(pix),2))
        # Keep the typeface's proportional spacing, especially for I/i/l.
        advance=round(f.getlength(ch)*16)
        # Reserve the full percent ink so right-aligned battery labels do not
        # clip the final glyph after LVGL rounds the advance to pixels.
        if size==10 and ch=='%': advance=max(advance,(l+w)*16)
        glyphs.append(f'{{.bitmap_index={idx},.adv_w={advance},.box_w={w},.box_h={h},.ofs_x={l},.ofs_y={-b}}}')
    body=['/* Noto Sans SC, SIL OFL 1.1; generated by tools/generate_badge_fonts.py. */','#include "lvgl.h"','static const uint8_t bitmap[]={']
    body+= [','.join(hex(x) for x in data[i:i+24])+',' for i in range(0,len(data),24)]
    body+=['};','static const lv_font_fmt_txt_glyph_dsc_t glyphs[]={',',\n'.join(glyphs),'};',
      'static const lv_font_fmt_txt_cmap_t cmaps[]={{.range_start=32,.range_length=95,.glyph_id_start=1,.type=LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY}};',
      'static const lv_font_fmt_txt_dsc_t descriptor={.glyph_bitmap=bitmap,.glyph_dsc=glyphs,.cmaps=cmaps,.cmap_num=1,.bpp=4,.bitmap_format=0};',
      f'const lv_font_t font_badge_{size}={{.get_glyph_dsc=lv_font_get_glyph_dsc_fmt_txt,.get_glyph_bitmap=lv_font_get_bitmap_fmt_txt,.line_height={size+4},.base_line={size//4+1},.dsc=&descriptor}};']
    if len(chars)>95:
        i=body.index('static const lv_font_fmt_txt_cmap_t cmaps[]={{.range_start=32,.range_length=95,.glyph_id_start=1,.type=LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY}};')
        body[i:i+1]=['static const uint16_t unicode[]={'+','.join(str(ord(c)-32) for c in chars)+'};',f'static const lv_font_fmt_txt_cmap_t cmaps[]={{{{.range_start=32,.range_length={ord(chars[-1])-31},.glyph_id_start=1,.unicode_list=unicode,.list_length={len(chars)},.type=LV_FONT_FMT_TXT_CMAP_SPARSE_TINY}}}};']
    (root/f'main/font_badge_{size}.c').write_text('\n'.join(body)+'\n',encoding='utf-8')
    print(f'font_badge_{size}: {len(data)} bytes')
